// docs/ai-workflow-setup.md renderer: recommended plugins + (for azure) the ado MCP note.

/** Render docs/ai-workflow-setup.md: recommended plugins + (for azure) the ado MCP note. */
export function renderSetupDoc(config) {
  const azure = config.ticketing?.backend === 'azure-devops';
  const lines = [
    '<!-- DO NOT EDIT — generated by `ai-dev-workflow init`; re-run init to refresh. -->',
    '',
    `# AI Workflow Setup — ${config.project?.name || 'your project'}`,
    '',
    'This workflow is designed for **Claude Code** with three recommended plugins / MCP',
    'servers. Install them once per machine (or per project where noted).',
    '',
    '## superpowers',
    '',
    'Skill library that drives the brainstorm → plan → implement workflow. Install from the',
    'official Claude Code plugin marketplace:',
    '',
    '```',
    '/plugin install superpowers@claude-plugins-official',
    '```',
    '',
    '## context7',
    '',
    'MCP server that fetches up-to-date library/framework documentation on demand. Run the',
    'guided setup and pick **Claude Code** as the target (handles API-key OAuth for you):',
    '',
    '```bash',
    'npx ctx7 setup',
    '```',
    '',
    'Manual alternative: point your MCP client at `https://mcp.context7.com/mcp` and pass your',
    'key via the `CONTEXT7_API_KEY` header.',
    '',
    '## serena',
    '',
    'MCP server providing semantic, symbol-level code navigation and editing. Add it to Claude',
    'Code (per project shown; use `--scope user` for all projects):',
    '',
    '```bash',
    'claude mcp add serena -- serena start-mcp-server --context claude-code --project "$(pwd)"',
    '```',
    '',
    'Install Serena itself first per its docs (`uv tool install -p 3.13 serena-agent`). Do **not**',
    'install Serena through a plugin marketplace — follow the Serena Quick Start.',
    '',
  ];
  if (azure) {
    lines.push(
      '## Azure DevOps `ado` MCP server',
      '',
      'For the `azure-devops` ticketing backend, `ai-dev-workflow generate` automatically merges an',
      '`ado` server entry into `.mcp.json` (the `@azure-devops/mcp` server handles its own auth).',
      'Nothing to install by hand — just run `generate` and reload your MCP servers.',
      '',
    );
  }
  lines.push(
    '## Next steps',
    '',
    '1. `npx github:marxxxx/ai-dev-workflow generate` — render the platform files.',
    '2. Commit `ai-project.json` and the generated `.claude/`, `.codex/`, `.opencode/`, `.agents/` dirs.',
    '',
  );
  return lines.join('\n');
}
