// docs/ai-workflow-setup.md renderer: recommended plugins + per-harness MCP server setup
// (+ for azure, the ado MCP note).

/**
 * Every MCP server below is added scoped to *this project only* — never to a harness's
 * global/user-wide config — so machines with multiple projects don't leak servers (or API
 * keys) across them.
 */
function context7Section() {
  return [
    '## context7',
    '',
    'MCP server that fetches up-to-date library/framework documentation on demand. Free to use',
    'anonymously; sign up at https://context7.com for an API key to raise the rate limit (optional).',
    '',
    '**Claude Code** — `--scope local` keeps it private to this project + machine (not written to',
    'the shared `.mcp.json`, not available to other projects):',
    '',
    '```bash',
    'claude mcp add --scope local --transport http context7 https://mcp.context7.com/mcp \\',
    '  --header "CONTEXT7_API_KEY: YOUR_API_KEY"',
    '```',
    '',
    '**Codex** — `codex mcp add` only writes to the global `~/.codex/config.toml`, so add it to a',
    'project-local `.codex/config.toml` instead (`env_http_headers` reads the key from your shell',
    "environment at runtime, so the key itself never lands in the committed file). Codex disables",
    'project-local config the first time it sees a new repo — accept the trust prompt on first run:',
    '',
    '```bash',
    'mkdir -p .codex',
    'cat >> .codex/config.toml <<' + "'EOF'",
    '',
    '[mcp_servers.context7]',
    'url = "https://mcp.context7.com/mcp"',
    '',
    '[mcp_servers.context7.env_http_headers]',
    'CONTEXT7_API_KEY = "CONTEXT7_API_KEY"',
    'EOF',
    '```',
    '',
    '**OpenCode** — add to (or create) `opencode.json` at the project root; it\'s safe to commit',
    'since the key is referenced via `{env:...}`, not inlined:',
    '',
    '```jsonc',
    '{',
    '  "$schema": "https://opencode.ai/config.json",',
    '  "mcp": {',
    '    "context7": {',
    '      "type": "remote",',
    '      "url": "https://mcp.context7.com/mcp",',
    '      "headers": { "CONTEXT7_API_KEY": "{env:CONTEXT7_API_KEY}" }',
    '    }',
    '  }',
    '}',
    '```',
    '',
  ];
}

function serenaSection() {
  return [
    '## serena',
    '',
    'MCP server providing semantic, symbol-level code navigation and editing.',
    '',
    '**Prerequisite** — install `uv` first (https://docs.astral.sh/uv/getting-started/installation/),',
    'then install Serena itself. Do **not** install Serena through a plugin marketplace — the MCP',
    'registration below is all it needs:',
    '',
    '```bash',
    'command -v uv >/dev/null 2>&1 || { echo "uv not found — install it first: https://docs.astral.sh/uv/getting-started/installation/" >&2; exit 1; }',
    'uv tool install -p 3.13 serena-agent',
    '```',
    '',
    '**Claude Code** (default scope is already `local` — private to this project + machine):',
    '',
    '```bash',
    'claude mcp add --scope local serena -- serena start-mcp-server --context claude-code --project "$(pwd)"',
    '```',
    '',
    '**Codex** — add to project-local `.codex/config.toml`:',
    '',
    '```bash',
    'mkdir -p .codex',
    'cat >> .codex/config.toml <<' + "'EOF'",
    '',
    '[mcp_servers.serena]',
    'startup_timeout_sec = 15',
    'command = "serena"',
    'args = ["start-mcp-server", "--project-from-cwd", "--context=codex"]',
    'EOF',
    '```',
    '',
    '**OpenCode** — add to `opencode.json`:',
    '',
    '```jsonc',
    '{',
    '  "$schema": "https://opencode.ai/config.json",',
    '  "mcp": {',
    '    "serena": {',
    '      "type": "local",',
    '      "command": ["serena", "start-mcp-server", "--context", "ide", "--project-from-cwd"],',
    '      "enabled": true',
    '    }',
    '  }',
    '}',
    '```',
    '',
  ];
}

function playwrightSection() {
  return [
    '## playwright',
    '',
    'MCP server that drives a real browser (via Playwright) for end-to-end testing and UI',
    'verification.',
    '',
    '**Claude Code**:',
    '',
    '```bash',
    'claude mcp add --scope local playwright -- npx @playwright/mcp@latest',
    '```',
    '',
    '**Codex** — add to project-local `.codex/config.toml`:',
    '',
    '```bash',
    'mkdir -p .codex',
    'cat >> .codex/config.toml <<' + "'EOF'",
    '',
    '[mcp_servers.playwright]',
    'command = "npx"',
    'args = ["@playwright/mcp@latest"]',
    'EOF',
    '```',
    '',
    '**OpenCode** — add to `opencode.json`:',
    '',
    '```jsonc',
    '{',
    '  "$schema": "https://opencode.ai/config.json",',
    '  "mcp": {',
    '    "playwright": {',
    '      "type": "local",',
    '      "command": ["npx", "@playwright/mcp@latest"],',
    '      "enabled": true',
    '    }',
    '  }',
    '}',
    '```',
    '',
  ];
}

/** Render docs/ai-workflow-setup.md: recommended plugins + per-harness MCP server setup. */
export function renderSetupDoc(config) {
  const azure = config.ticketing?.backend === 'azure-devops';
  const lines = [
    '<!-- DO NOT EDIT — generated by `ai-dev-workflow init`; re-run init to refresh. -->',
    '',
    `# AI Workflow Setup — ${config.project?.name || 'your project'}`,
    '',
    'This workflow supports **Claude Code**, **Codex**, and **OpenCode**, plus one recommended',
    'plugin and three recommended MCP servers. Install what your harness(es) need — every MCP',
    'server is scoped to this project only (see note below each), never installed globally.',
    '',
    '## superpowers',
    '',
    'Skill library that drives the brainstorm → plan → implement workflow (Claude Code plugin —',
    'no Codex/OpenCode equivalent). Install from the official Claude Code plugin marketplace:',
    '',
    '```',
    '/plugin install superpowers@claude-plugins-official',
    '```',
    '',
    ...context7Section(),
    ...serenaSection(),
    ...playwrightSection(),
  ];
  if (azure) {
    lines.push(
      '## Azure DevOps `ado` MCP server',
      '',
      'For the `azure-devops` ticketing backend, `ai-dev-workflow generate` automatically merges an',
      '`ado` server entry into `.mcp.json` (the `@azure-devops/mcp` server handles its own auth).',
      'Nothing to install by hand — just run `generate` and reload your MCP servers.',
      '',
    );
  }
  lines.push(
    '## Next steps',
    '',
    '1. `npx github:marxxxx/ai-dev-workflow generate` — render the platform files.',
    '2. Commit `ai-project.json` and the generated `.claude/`, `.codex/`, `.opencode/`, `.agents/` dirs.',
    '',
  );
  return lines.join('\n');
}
